### ISSUE TITLE
Sensors module doesn't show  three digits on temperatures above 99°.

### ISSUE THREAD

**Issue by dpkg-i-foo-deb** [tobi-wan-kenobi/bumblebee-status#787]
Affected module: Sensors

Description:
I guess most people don't have hardware whose temperatures raise above 99°. However, my processor sometimes goes up to 104, so the main problem is the sensors module can't show anything above 99, it will display a 10...

Here is a little example of the output when my hardware goes +99. I don't know if I missed something in the config, any clues?

![2021-05-09_16-21](https://user-images.githubusercontent.com/80849765/117587299-da824500-b0e2-11eb-9182-c92bd458eccc.png)

```
bar {
        status_command ~/.i3/bumblebee-status/bumblebee-status \
                -m cmus cpu cpu2 sensors memory load disk:root disk:home progress \
                -p cmus.format={artist}{file2} sensors.path=/sys/class/thermal/thermal_zone6/temp sensors.show_freq=false progress.placeholder="No Current Processes" cpu2.layout=cpu2.coresload cpu2.colored=0 root.path=/ home.path=/home \
                -t dracula-powerline
        position bottom
        workspace_buttons no
        font pango:Inconsolata 11.2

        tray_output primary
}
```

**Comment by tobi-wan-kenobi** [comment]
Looking at the code, that *should* not happen - can you please post the output of "sensors -u" in that situation?

Maybe the parsing in bumblebee is wrong.

Thanks a lot in advance!

**Comment by dpkg-i-foo-deb** [comment]
Here is the sensors -u output when my PC is about to melt. Package id 0 is the sensor I have set to monitor in the config.

```
sensors -u
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 101.000
  temp1_max: 87.000
  temp1_crit: 105.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 93.000
  temp2_max: 87.000
  temp2_crit: 105.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 101.000
  temp3_max: 87.000
  temp3_crit: 105.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 101.000
  temp4_max: 87.000
  temp4_crit: 105.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 94.000
  temp5_max: 87.000
  temp5_crit: 105.000
  temp5_crit_alarm: 0.000

acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 100.000
  temp1_crit: 128.000
temp2:
  temp2_input: 69.000
  temp2_crit: 128.000
temp3:
  temp3_input: 54.000
  temp3_crit: 128.000
temp4:
  temp4_input: 62.000
  temp4_crit: 128.000
temp5:
  temp5_input: 41.000
  temp5_crit: 128.000
temp6:
  temp6_input: 0.000
  temp6_crit: 128.000

radeon-pci-0100
Adapter: PCI adapter
temp1:
  temp1_input: 69.500
  temp1_crit: 120.000
  temp1_crit_hyst: 90.000
```
