### ISSUE TITLE
minor docs request - listing viable parameters for nic module

### ISSUE THREAD

**Issue by dvdmrn** [tobi-wan-kenobi/bumblebee-status#836]
### ~~Feature~~ Docs Request

Would it be possible to update the docs to include viable nic parameter values?

I want to configure the nic module so that it only displays the wifi name and ip. Right now it shows so much information that it goes off the screen. In the docs it says:

```
Parameters:

        nic.exclude: Comma-separated list of interface prefixes (supporting regular expressions) to exclude (defaults to ‘lo,virbr,docker,vboxnet,veth,br,.*:avahi’)
        nic.include: Comma-separated list of interfaces to include
        nic.states: Comma-separated list of states to show (prefix with ‘^’ to invert - i.e. ^down -> show all devices that are not in state down)
        nic.format: Format string (defaults to ‘{intf} {state} {ip} {ssid}’)
```
So I would presumably be supplying extra arguments to nic.exclude or nic.include. But nowhere in the docs does it list the arguments that I need to supply (e.g. "name", "ip", "state", etc.)
Does this exist anywhere, and if not, can a list be included in the docs? I would add it but I do not know where the nic module lives and how it is configured
