### ISSUE TITLE
Parameter names get converted to lowercase when using toml config file

### ISSUE THREAD

**Issue by TheEdgeOfRage** [tobi-wan-kenobi/bumblebee-status#992]
#### Description
Affected module: config
Version used: latest git

I use a toml config file to define all of my parameters. The problematic ones in this case, are the pulsectl pretty name params. The parameter key gets converted to lower case (presumably during toml parsing), while the pulsectl lib returns the properly capitalized name. The pulsectl module then fails to look up the params, cause the names don't match. Adding a `.lower()` call on the output from pulsectl fixes this issue, but breaks parameters passed in through the command line.

[Related issue](https://github.com/tobi-wan-kenobi/bumblebee-status/issues/989)

#### How to reproduce
Create a toml config for bumblebee, similar to this:

```toml
[core]
modules=pulseout

[module-parameters]
pulseout.showdevicename=true
pulseout.in=alsa_output.usb-Topping_DX3_Pro_-00.playback.0.0=Headphones
```

Just adjust the device name to one on your own machine that has capital letters.
Starting bumblebee with this config, will still show the original name.
